Tommaso
develhope-java10/SQLReview pull request #5
Opened 2023-04-09 11:46 UTC by TTranchese

2023-04-18 14:15 UTC, aegroto requested changes

2023-04-18 14:15 UTC, aegroto commented on tommaso/es2-1.sql
> +FROM Tutors
Qui non dovrebbe servirti Tutors, visto che ti chiede di stampare solo il nome del corso.

2023-04-18 14:15 UTC, aegroto commented on tommaso/es2-4.sql
> +HAVING COUNT(id) < 2;
qui dev'essere "= 1", altrimenti anche quando un tutor non lavora in nessun corso viene elencato

2023-04-19 10:54 UTC, TTranchese commented on tommaso/es2-1.sql
> +FROM Tutors
Diciamo che l'ho fatto per completezza e per mettermi un po' di ordine mentale

2023-04-19 11:58 UTC, aegroto approved these changes

2023-04-19 11:58 UTC, merged